### ISSUE TITLE
Non-NSObject type support

### ISSUE THREAD

**Issue by tuyendv2** [RxSwiftCommunity/NSObject-Rx#11]
This module is helpful. Can we have something like this for non-NSObject type?

**Comment by ashfurrow** [comment]
Good question! The library currently relies on the Objective-C runtime's associated objects feature, which as far as I know doesn't have an equivalent for Swift-only types. The only solution that comes to mind is to use a global lookup table (a static dictionary `[AnyObject: DisposeBag]`). It's... not a great solution :sweat_smile: But I'd really like this feature on non-ObjC types, too. I'll think about other solutions, and if anyone has suggestions, we're all :ear:s

**Comment by solidfox** [comment]
Isn't the Obj-C runtime's associated objects feature basically a global lookup table? So as far as smelly global state goes it's the same smell. Problem is that `[AnyObject: DisposeBag]` would keep the `AnyObject`s and thus the `DisposeBag`s in memory forever since we have no weak pointer dictionaries in swift yet. Once we have that I believe such a solution would be sleeker than the rather archaic associated objects feature.

**Comment by freak4pc** [comment]
I don't think this is a super achievable/needed thing for RxSwift >3 because the way Reactive parts are in extensions of the Reactive protocol which are bound to NSObjects as well (e.g. `element.rx.observable`). 

Since this hasn't been active for a year now, I'll be closing this. If you feel like we should re-open the discussion we can re-open.
