### ISSUE TITLE
Is this the same effect of rx_disposeBag?

### ISSUE THREAD

**Issue by frogcjn** [RxSwiftCommunity/NSObject-Rx#18]
``` swift
_ = some_rx_task
     .take_until(rx_deallocated)
     ....
```

is the same effect of NSObject-Rx

``` swift
some_rx_task
     ...
     .addDisposeTo(rx_disposeBag)
```

?

**Comment by ashfurrow** [comment]
Good question! Often, the effect is the same, but not always. 

In the first example, you're creating an observable that stops when your object is deallocated. Even if the observable _would_ have sent further values, it definitely won't because `takeUntil` stops it.

In the second example, you're only _subscribing_ to an observable as long as your dispose bag is around (until you're deallocated). However, even after you're no longer in memory, the `some_rx_task` could still send events.

It's a subtle difference. Generally you want the second example.
