### ISSUE TITLE
Can't compile with Cocopods and Xcode 12

### ISSUE THREAD

**Issue by alouanemed** [RxSwiftCommunity/NSObject-Rx#83]
```

> Copying Moya-umbrella.h

[x] /Users/alouanemed/Projects/a-iOS/Pods/_Prebuild/Moya/Sources/RxMoya/MoyaProvider+Rx.swift:2:8: compiling for iOS 10.0, but module 'RxSwift' has a minimum deployment target of iOS 12.0: /Users/alouanemed/Projects/a-iOS/Pods/build/Release-iphoneos/RxSwift/RxSwift.framework/Modules/RxSwift.swiftmodule/arm64-apple-ios.swiftmodule

import RxSwift
       ^


> Linking Alamofire
> Linking Alamofire
```

**Comment by ashfurrow** [comment]
Hi there, looks like an issue with your target iOS version:

```
compiling for iOS 10.0, but module 'RxSwift' has a minimum deployment target of iOS 12.0
```

This is odd since RxSwift should work as far back as iOS 8:

https://github.com/ReactiveX/RxSwift/blob/92bf03ec1f1bedcd041fa1074896acd621cbca18/RxSwift.podspec#L30

Moya, and its `RxSwift` subspec, also support iOS 10:

https://github.com/Moya/Moya/blob/218c2f3462ff1e8b85283b94829afd54a9850664/Moya.podspec#L16

I'm a little confused about this error then. Can you share your Podfile?

**Comment by ShenYj** [comment]
it's time to close it.
